import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

import SplashScreen from "@/components/splash";
import { ThemeProvider } from "@/components/theme-provider";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Piersec Marketing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={montserrat.variable} suppressHydrationWarning>
      <body className={montserrat.className}>
        <ThemeProvider>
          <SplashScreen />

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
